### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by AndrewSB** [traderepublic/Cilicon#2]
hey! i was looking to create a github action worker. i've made it through a few of the setup steps, but the error messages from the runner are really hard to decipher. is there a version i can run that has more verbose error messages/stack traces so i can understand what's wrong with my configuration? 

<img width="970" alt="Screenshot 2023-01-26 at 12 39 46 PM" src="https://user-images.githubusercontent.com/3814772/214945772-8f24e2eb-02e3-40e7-9d48-9a5b889e34df.png">

also, i saw the medium post that was written about the release of this, are there any other resources that walk through setting up a github app + configuration for a runner using Cilicon?

**Comment by Marcocanc** [comment]
Hi @AndrewSB, sorry for the late response!
Cilicon relies on `Error`'s `localizedDescription` for displaying errors, which should provide a human readable error description to the user. It looks like SwiftJWT may not be implementing this correctly. I will have a look and hopefully fix it soon.
Since it's JWT related I'm almost certain that the `pem` key you're using is the problem. Could you try re-generating it?

**Comment by Marcocanc** [comment]
The error description should be fixed by https://github.com/Kitura/Swift-JWT/pull/111

**Comment by AndrewSB** [comment]
awesome! thanks @Marcocanc
